 
<?php
/**
*This module can convert date if you have 'year', 'day of year' (1 to 365) and 'hour', 'minute' if you need.
*You must set also the date 'format' see at @link: http://php.net/manual/en/function.date.php
*It give you a date in gregorian format, you can modify this module to add more calendar types maybe.
*So, @params:
* $time_data=array($year,$day,$hour,$minute)
* $date_format="d/m/Y H:m:i" //maybe
*/
/**Example:
*$year=2014;
*$dia=338;
*$hora=10;
*$minuto=30;
*$date_format="d/m/Y H:i";
*/

function jd2gdate($time_date=array('year','day','hour','minute'),$date_format){
$year=$time_date['year'];
$day=$time_date['day'];
$hour=$time_date['hour'];
$minute=$time_date['minute'];
$year_jd=gregoriantojd(1,1,$year);
$day_julian=$year_jd+$day-1;
$date_gregorian=cal_from_jd($day_julian,CAL_GREGORIAN);
$time=mktime($hour,$minute,0,$date_gregorian['month'],$date_gregorian['day'],$date_gregorian['year']);
$fecha=date($date_format,$time);
}

/*Try it on html
*echo "<html>";
*echo "<p>El año es:<p>";
*echo "<body>{$year}</body>";
*echo "<p>El año es en dia juliano:<p>";
*echo "<body>{$year_jd}</body>";
*echo "<p>El 4 de diciembre, 338:<p>";
*echo "<body>{$dia_juliano}</body>";
*echo "<p>En dia gregoriano:<p>";
*echo "<pre>";print_r($fecha_gregoriana);echo "</pre>";
*echo "<p>La fecha y hora es:<p>";
*echo "<p>{$fecha}</p>";
*/